// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.0
// source: pane-api/proto/pane.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PaneService_Spawn_FullMethodName    = "/pane.PaneService/Spawn"
	PaneService_Exec_FullMethodName     = "/pane.PaneService/Exec"
	PaneService_Snapshot_FullMethodName = "/pane.PaneService/Snapshot"
	PaneService_Fork_FullMethodName     = "/pane.PaneService/Fork"
	PaneService_Destroy_FullMethodName  = "/pane.PaneService/Destroy"
)

// PaneServiceClient is the client API for PaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaneServiceClient interface {
	Spawn(ctx context.Context, in *SpawnRequest, opts ...grpc.CallOption) (*SpawnResponse, error)
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (PaneService_ExecClient, error)
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*ForkResponse, error)
	Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error)
}

type paneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaneServiceClient(cc grpc.ClientConnInterface) PaneServiceClient {
	return &paneServiceClient{cc}
}

func (c *paneServiceClient) Spawn(ctx context.Context, in *SpawnRequest, opts ...grpc.CallOption) (*SpawnResponse, error) {
	out := new(SpawnResponse)
	err := c.cc.Invoke(ctx, PaneService_Spawn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paneServiceClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (PaneService_ExecClient, error) {
	stream, err := c.cc.NewStream(ctx, &PaneService_ServiceDesc.Streams[0], PaneService_Exec_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &paneServiceExecClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PaneService_ExecClient interface {
	Recv() (*ExecResponse, error)
	grpc.ClientStream
}

type paneServiceExecClient struct {
	grpc.ClientStream
}

func (x *paneServiceExecClient) Recv() (*ExecResponse, error) {
	m := new(ExecResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *paneServiceClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, PaneService_Snapshot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paneServiceClient) Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*ForkResponse, error) {
	out := new(ForkResponse)
	err := c.cc.Invoke(ctx, PaneService_Fork_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paneServiceClient) Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error) {
	out := new(DestroyResponse)
	err := c.cc.Invoke(ctx, PaneService_Destroy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaneServiceServer is the server API for PaneService service.
// All implementations must embed UnimplementedPaneServiceServer
// for forward compatibility
type PaneServiceServer interface {
	Spawn(context.Context, *SpawnRequest) (*SpawnResponse, error)
	Exec(*ExecRequest, PaneService_ExecServer) error
	Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	Fork(context.Context, *ForkRequest) (*ForkResponse, error)
	Destroy(context.Context, *DestroyRequest) (*DestroyResponse, error)
	mustEmbedUnimplementedPaneServiceServer()
}

// UnimplementedPaneServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPaneServiceServer struct {
}

func (UnimplementedPaneServiceServer) Spawn(context.Context, *SpawnRequest) (*SpawnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Spawn not implemented")
}
func (UnimplementedPaneServiceServer) Exec(*ExecRequest, PaneService_ExecServer) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedPaneServiceServer) Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedPaneServiceServer) Fork(context.Context, *ForkRequest) (*ForkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fork not implemented")
}
func (UnimplementedPaneServiceServer) Destroy(context.Context, *DestroyRequest) (*DestroyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedPaneServiceServer) mustEmbedUnimplementedPaneServiceServer() {}

// UnsafePaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaneServiceServer will
// result in compilation errors.
type UnsafePaneServiceServer interface {
	mustEmbedUnimplementedPaneServiceServer()
}

func RegisterPaneServiceServer(s grpc.ServiceRegistrar, srv PaneServiceServer) {
	s.RegisterService(&PaneService_ServiceDesc, srv)
}

func _PaneService_Spawn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaneServiceServer).Spawn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaneService_Spawn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaneServiceServer).Spawn(ctx, req.(*SpawnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaneService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PaneServiceServer).Exec(m, &paneServiceExecServer{stream})
}

type PaneService_ExecServer interface {
	Send(*ExecResponse) error
	grpc.ServerStream
}

type paneServiceExecServer struct {
	grpc.ServerStream
}

func (x *paneServiceExecServer) Send(m *ExecResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PaneService_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaneServiceServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaneService_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaneServiceServer).Snapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaneService_Fork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaneServiceServer).Fork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaneService_Fork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaneServiceServer).Fork(ctx, req.(*ForkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaneService_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaneServiceServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaneService_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaneServiceServer).Destroy(ctx, req.(*DestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaneService_ServiceDesc is the grpc.ServiceDesc for PaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pane.PaneService",
	HandlerType: (*PaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Spawn",
			Handler:    _PaneService_Spawn_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _PaneService_Snapshot_Handler,
		},
		{
			MethodName: "Fork",
			Handler:    _PaneService_Fork_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _PaneService_Destroy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _PaneService_Exec_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pane-api/proto/pane.proto",
}
